services:
  app:
    build: .
    container_name: laravel-app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    user: www-data:www-data
    expose:
      - 80
      - 443
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: laravel-app-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: crud
      MYSQL_USER: test
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db-data:
    driver: local

networks:
  app-network:
    driver: bridge
