services:
  app:
    build: .
    container_name: laravel-app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./app/:/var/www/app
      - ./config/:/var/www/config
      - ./database/:/var/www/database
      - ./public/:/var/www/public
      - ./resources/:/var/www/resources
      - ./routes/:/var/www/routes
      - ./tests/:/var/www/tests
      - ./composer.json/:/var/www/composer.json
      - ./composer.lock/:/var/www/composer.lock
      - ./.env:/var/www/.env
      - ./package-lock.json:/var/www/package-lock.json
      - ./package.json:/var/www/package.json
      - ./phpunit.xml:/var/www/phpunit.xml
      - ./postcss.config.js:/var/www/postcss.config.js
      - ./LICENSE:/var/www/LICENSE

    user: www-data:www-data
    expose:
      - 80
      - 443
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: laravel-app-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: crud
      MYSQL_USER: test
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db-data:
    driver: local

networks:
  app-network:
    driver: bridge
